import dash
import pandas as pd
from dash import Input, Output, dcc, html
import dash_bootstrap_components as dbc

import server_function as sf
import component_function as comp_fun


q1 = pd.read_excel("C:/Users/AYOMIDE/PycharmProjects/variable_summary/IGR_app/IGR_2021.xlsx", sheet_name = "Q1_sheet")
q2 = pd.read_excel("C:/Users/AYOMIDE/PycharmProjects/variable_summary/IGR_app/IGR_2021.xlsx", sheet_name = "Q2_sheet")
half_year = pd.read_excel("C:/Users/AYOMIDE/PycharmProjects/variable_summary/IGR_app/IGR_2021.xlsx", sheet_name = "Half_year")

q1 = sf.clean_data(q1)
q2 = sf.clean_data(q2)
half_year = sf.clean_data(half_year)

igr_df = sf.concat_periods(q1, q2, half_year)


all_location = {
    "State": q1["State"].unique().tolist(),
    "Zone" : q1["Zone"].unique().tolist()
}

revenue_source = ['PAYE', 'Direct Assessment', 'Road Tax', 'Other Taxes', 'MDAs', 'Total Tax', 'Grand Total']


app = dash.Dash(__name__, external_stylesheets = [dbc.themes.MATERIA], suppress_callback_exceptions=True)


app.layout = dbc.Container(
    [
        html.Div(
            [
                html.H3("Internally Generated Revenue Analysis", className= "page-header-title"),

                html.P(
                    """
                    Analysis of the various source of revenue generated by each state in Nigeria at state level
                     and also within geo-political zones for the first, second and half year of 2021.
                    """,
                    className= "page-header-description"
                )
            ],
            className= "header-title-div "
        ),

        html.Br(),

        html.Div(
            [
                html.Div(
                    [
                        dcc.Tabs(
                            [
                                dcc.Tab(
                                    [
                                        html.Div(
                                            [
                                                html.Div(
                                                    [
                                                        html.Div(
                                                            [
                                                                comp_fun.dropdown_menu(
                                                                    drop_radio_id = "in_ri_get_period"
                                                                )
                                                            ],
                                                            className = "input-position",
                                                        ),

                                                        html.Div(
                                                            [
                                                                html.Label("Select Level", className="label"),
                                                                comp_fun.state_zone_radioitem(
                                                                    radio_id = "in_ri_get_revenue_level",
                                                                    selected = "State"
                                                                )
                                                            ],
                                                            className = "input-position",
                                                        ),

                                                        html.Div(
                                                            [
                                                                html.Label("Select Revenue Source", className="label"),
                                                                dcc.Dropdown(id = "in_dd_get_revenue",
                                                                             options = [{"label": r, "value": r}
                                                                                        for r in revenue_source],
                                                                             value="Grand Total",)
                                                            ],
                                                            className = "input-pos-dropdown",
                                                        ),
                                                    ],
                                                    className = "input-select-div input-select-large"
                                                ),
                                            ],
                                            className= "div-top"
                                        ),

                                        html.Br(),

                                        html.Div(
                                            [
                                                html.Div(
                                                    children = [],
                                                    id = "out_plt_get_revenue",
                                                    className= "graph-card"
                                                )
                                            ]
                                        )
                                    ],
                                    id = "in_get_revenue_state",  # ----------------------------------------------|Tab 1
                                    label = "Revenue Source",
                                    className= "page-tab",
                                    selected_className= "tab-selected"
                                ),

                                dcc.Tab(
                                    [
                                        html.Div(
                                            [
                                                html.Div(
                                                    [
                                                        html.Div(
                                                            [
                                                                comp_fun.dropdown_menu(
                                                                    drop_radio_id = "in_ri_total_igr_period"
                                                                )
                                                            ],
                                                            className = "input-position",
                                                        ),

                                                        html.Div(
                                                            [
                                                                html.Label("Select Level", className="label"),
                                                                comp_fun.state_zone_radioitem(
                                                                    radio_id = "in_ri_total_igr_level",
                                                                    selected = "State")
                                                            ],
                                                            className = "input-position",
                                                        ),

                                                        html.Div(
                                                            [
                                                                html.Label("Select Location", className="label"),
                                                                dcc.Dropdown(id = "in_dd_total_igr",)
                                                            ],
                                                            className = "input-pos-dropdown"
                                                        ),
                                                    ],
                                                    className= "input-select-div input-select-large"
                                                ),
                                            ],
                                            className= "div-top"
                                        ),

                                        html.Br(),

                                        html.Div(
                                            [
                                                html.Div(
                                                    children=[],
                                                    id="out_plt_total_igr",
                                                    className="graph-card"
                                                )
                                            ]
                                        )
                                    ],
                                    id = "in_total_igr",  # -----------------------------------------------------| Tab 2
                                    label = "Total IGR",
                                    className="page-tab",
                                    selected_className="tab-selected"
                                ),

                                dcc.Tab(
                                    [
                                        html.Div(
                                            [
                                                html.Div(
                                                    [
                                                        html.Div(
                                                            [
                                                                comp_fun.dropdown_menu(
                                                                    drop_radio_id="in_ri_state_region"
                                                                )
                                                            ],
                                                            className = "input-position",
                                                        ),

                                                        html.Div(
                                                            [
                                                                html.Label("Select Zone", className= "label"),

                                                                dcc.Dropdown(id = "in_dd_state_region_zone",
                                                                             options= [{"label": z, "value": z}
                                                                                       for z in igr_df["Zone"].unique()],
                                                                             value= "South East")
                                                            ],
                                                            className = "input-pos-dropdown",
                                                        ),

                                                        html.Div(
                                                            [
                                                                html.Label("Select Revenue", className= "label"),

                                                                dcc.Dropdown(id="in_dd_state_region_revenue",
                                                                             options=[{"label": r, "value": r}
                                                                                      for r in revenue_source],
                                                                             value="Grand Total")
                                                            ],
                                                            className= "input-pos-dropdown",
                                                        ),
                                                    ],
                                                    className= "input-select-div input-select-large"
                                                ),
                                            ],
                                            className= "div-top"
                                        ),

                                        html.Div(
                                            [
                                                html.Div(
                                                    children=[],
                                                    id="out_plt_state_region",
                                                    className="graph-card"
                                                )
                                            ],
                                            className= "div-top"
                                        )
                                    ],
                                    id = "in_state_region",  # --------------------------------------------------| Tab 3
                                    label= "State within Zone Revenue",
                                    className="page-tab",
                                    selected_className="tab-selected"
                                ),

                                dcc.Tab(
                                    [
                                        html.Div(
                                            [
                                                html.Div(
                                                    [
                                                        html.Div(
                                                            [
                                                                html.Label("Select Revenue", className="label"),

                                                                dcc.Dropdown(id="in_dd_change",
                                                                             options = [{"label": r, "value": r}
                                                                                        for r in revenue_source],
                                                                             value="Grand Total")
                                                            ],
                                                            className ="input-pos-dropdown",
                                                        ),
                                                    ],
                                                    className="input-select-small input-select-div"
                                                ),
                                            ],
                                            className="div-top"
                                        ),

                                        html.Div(
                                            [
                                                html.Div(
                                                    children=[],
                                                    id="out_plt_change",
                                                    className="graph-card"
                                                )
                                            ],
                                            className="div-top"
                                        )
                                    ],
                                    id="in_percent_change",  # --------------------------------------------------| Tab 4
                                    label="% Increase/Decrease",
                                    className="page-tab",
                                    selected_className="tab-selected"
                                ),

                                dcc.Tab(
                                    [
                                        html.Div(
                                            [
                                                html.Div(
                                                    [
                                                        html.Div(
                                                            [
                                                                comp_fun.dropdown_menu(
                                                                    drop_radio_id="in_ri_summary_period"
                                                                )
                                                            ],
                                                            className="input-position",
                                                        ),

                                                        html.Div(
                                                            [
                                                                dbc.DropdownMenu(
                                                                    [
                                                                        dbc.DropdownMenuItem(
                                                                            [
                                                                                dbc.RadioItems(
                                                                                    id = "in_ri_summary_type",
                                                                                    options=[
                                                                                        {"label": "Total",
                                                                                         "value": "sum"},
                                                                                        {"label": "Average",
                                                                                         "value": "mean"},
                                                                                        {"label": "Median",
                                                                                         "value": "median"}
                                                                                    ],
                                                                                    value= "sum"
                                                                                )
                                                                            ]
                                                                        )
                                                                    ],
                                                                    label = "Summary Type",
                                                                ),
                                                            ],
                                                            className= "input-position",
                                                        )
                                                    ],
                                                    className="input-select-medium input-select-div"
                                                ),
                                            ],
                                            className="div-top"
                                        ),

                                        html.Div(
                                            [
                                                html.Div(
                                                    children=[],
                                                    id="out_plt_summary",
                                                    className="graph-card"
                                                )
                                            ],
                                            className="div-top"
                                        )
                                    ],
                                    id="in_revenue_summary",  # -------------------------------------------------| Tab 5
                                    label="Revenue Summary",
                                    className="page-tab",
                                    selected_className="tab-selected"
                                ),

                            ],
                            id = "first_tab"
                        )
                    ],
                ),
            ],
        ),
    ],
    fluid = True
)





@app.callback(
    Output("out_plt_get_revenue", "children"),
    [Input("in_ri_get_period", "value"),
     Input("in_ri_get_revenue_level", "value"),
     Input("in_dd_get_revenue", "value")]
)
def create_revenue_plot(period, level, revenue_type):
    ser_output = sf.revenue_plot(df = igr_df, period = period, revenue_type = revenue_type, level = level)

    return comp_fun.create_graph(ser_output)

# Sources Of Internally Generated Revenue by State & Zone ============================================================||
@app.callback(
    Output("in_dd_total_igr", "options"),
    [Input("in_ri_total_igr_level", "value")]
)
def set_location_options(select_level):
    return [{"label": l, "value": l} for l in all_location[select_level]]

@app.callback(
    Output("in_dd_total_igr", "value"),
    [Input("in_dd_total_igr", "options")]
)
def set_initial_value(available_options):
    return available_options[0]["value"]



@app.callback(
    Output("out_plt_total_igr", "children"),
    [Input("in_ri_total_igr_period", "value"),
     Input("in_ri_total_igr_level", "value"),
     Input("in_dd_total_igr", "value")]
)
def create_total_igr(period, level, location_var):
    ser_output = sf.total_igr_output(df = igr_df, period= period, level= level, location_var= location_var)

    return comp_fun.create_graph(ser_output)


# Zonal States Revenue =======================================================================================|||
@app.callback(
    Output("out_plt_state_region", "children"),
    [Input("in_ri_state_region", "value"),
     Input("in_dd_state_region_zone", "value"),
     Input("in_dd_state_region_revenue", "value")]
)
def create_zonal_revenue(period, zone, revenue_type):
    ser_output =  sf.zonal_revenue_output(df = igr_df, period= period, zone= zone, revenue_type= revenue_type)

    return comp_fun.create_graph(ser_output)

# Increase / decrease ==========================================================================================||
@app.callback(
    Output("out_plt_change", "children"),
    [Input("in_dd_change", "value")]
)
def create_change(revenue_type):
    ser_output = sf.revenue_change_output(df1= q1, df2= q2, revenue_type = revenue_type)

    return comp_fun.create_graph(ser_output)

# Revenue summary =========================================================================||
@app.callback(
    Output("out_plt_summary", "children"),
    [Input("in_ri_summary_period", "value"),
     Input("in_ri_summary_type", "value")]
)
def create_summary(period, summary):
    ser_output = sf.revenue_summary_output(df = igr_df, period= period, summary= summary)

    return comp_fun.create_graph(ser_output)


if __name__ == "__main__":
    app.run_server(debug = True)